CREATE DATABASE DUAN1;
GO
USE DUAN1;
GO

CREATE TABLE KHACHHANG(
	ID INT PRIMARY KEY IDENTITY,
	MAKH VARCHAR(05),
	TEN NVARCHAR(20),
	SODIENTHOAI VARCHAR(10),
	DIACHI NVARCHAR(30),
	GIOITINH INT,
	NGAYSINH DATE
);

CREATE TABLE NHANVIEN(
	ID INT PRIMARY KEY IDENTITY,
	MANV VARCHAR(05),
	TEN NVARCHAR(20),
	SODIENTHOAI VARCHAR(10),
	EMAIL VARCHAR(30),
	PASS NVARCHAR(30),
	GIOITINH INT,
	CHUCVU INT,
	TRANGTHAI BIT
);

CREATE TABLE THANHTOAN(
	ID INT PRIMARY KEY IDENTITY,
	PHUONGTHUC INT
);

CREATE TABLE SANPHAM(
	ID INT PRIMARY KEY IDENTITY,
	MASP VARCHAR(05),
	TEN NVARCHAR(50),
	TRANGTHAI BIT,
);

CREATE TABLE THUONGHIEU(
	ID INT PRIMARY KEY IDENTITY,
	MA VARCHAR(05),
	TEN NVARCHAR(20),
	NGUONGOC NVARCHAR(20)
);

CREATE TABLE KIEUDANG(
	ID INT PRIMARY KEY IDENTITY,
	MA VARCHAR(05),
	TEN NVARCHAR(20)
);

CREATE TABLE LOAI(
	ID INT PRIMARY KEY IDENTITY,
	TEN NVARCHAR(20)
);

CREATE TABLE KICHCO(
	ID INT PRIMARY KEY IDENTITY,
	MA VARCHAR(05),
	Inch INT
);

CREATE TABLE MANHINH(
	ID INT PRIMARY KEY IDENTITY,
	MA VARCHAR(05),
	TEN NVARCHAR(20)
);

CREATE TABLE DOPHANGIAI(
	ID INT PRIMARY KEY IDENTITY,
	MA VARCHAR(05),
	TEN NVARCHAR(20)
);

CREATE TABLE SANPHAMCHITIET(
	ID INT PRIMARY KEY IDENTITY,
	MASPCT VARCHAR(05),
	ID_SP INT FOREIGN KEY REFERENCES SANPHAM(ID),
	ID_THUONGHIEU INT FOREIGN KEY REFERENCES THUONGHIEU(ID),
	ID_KIEUDANG INT FOREIGN KEY REFERENCES KIEUDANG(ID),
	ID_LOAI INT FOREIGN KEY REFERENCES LOAI(ID),
	ID_KICHCO INT FOREIGN KEY REFERENCES KICHCO(ID),
	ID_MANHINH INT FOREIGN KEY REFERENCES MANHINH(ID),
	ID_PHANGIAI INT FOREIGN KEY REFERENCES DOPHANGIAI(ID),
	SOLUONG INT,
	DONGIA MONEY,
	TRANGTHAI BIT
);
CREATE TABLE HOADON(
	ID INT PRIMARY KEY IDENTITY,
	MAHD VARCHAR(05),
	ID_KH INT FOREIGN KEY REFERENCES KHACHHANG(ID),
	ID_NV INT FOREIGN KEY REFERENCES NHANVIEN(ID),
	ID_THANHTOAN INT FOREIGN KEY REFERENCES THANHTOAN(ID),
	TEN NVARCHAR(20),
	SODIENTHOAI VARCHAR(10),
	NGAY DATE,
	TONGTIEN INT,
	TRANGTHAI INT
);
CREATE TABLE HOADONCHITIET(
	ID INT PRIMARY KEY IDENTITY,
	MAHDCT VARCHAR(05),
	ID_HD INT FOREIGN KEY REFERENCES HOADON(ID),
	ID_SPCT INT FOREIGN KEY REFERENCES SANPHAMCHITIET(ID),
	SOLUONG INT,
	DONGIA MONEY
);
CREATE TABLE PHIEUGIAMGIA(
	MAPHIEU VARCHAR(05) PRIMARY KEY,
	ID_HD INT FOREIGN KEY REFERENCES HOADON(ID),
	PHANTRAM INT,
	NGAYTAO DATE,
	NGAYHETHAN DATE,
	TRANGTHAI INT
);

-- Thêm dữ liệu cho bảng KHACHHANG
INSERT INTO KHACHHANG (MAKH, TEN, SODIENTHOAI, DIACHI, GIOITINH, NGAYSINH) VALUES
('KH001', N'Nguyễn Văn An', '0901234567', N'123 Lý Thường Kiệt', 1, '1990-01-01'),
('KH002', N'Trần Thị Bình', '0912345678', N'456 Trần Hưng Đạo', 0, '1991-02-02'),
('KH003', N'Lê Văn Công', '0923456789', N'789 Nguyễn Trãi', 1, '1992-03-03'),
('KH004', N'Phạm Thị Duyên', '0934567890', N'321 Hai Bà Trưng', 0, '1993-04-04'),
('KH005', N'Hoàng Văn Tiến', '0945678901', N'654 Bà Triệu', 1, '1994-05-05');
select * from KHACHHANG

-- Thêm dữ liệu cho bảng NHANVIEN
INSERT INTO NHANVIEN (MANV, TEN, SODIENTHOAI, EMAIL, PASS, GIOITINH, CHUCVU, TRANGTHAI) VALUES
('NV001', N'Nguyễn Minh Anh', '0901234567', 'anh.nguyen@example.com', 'anhnm', 1, 1, 1),
('NV002', N'Trần Thu Hà', '0912345678', 'ha.tran@example.com', 'hatt', 0, 2, 1),
('NV003', N'Lê Văn Chiến', '0923456789', 'chien.le@example.com', 'chienlv', 1, 1, 1),
('NV004', N'Phạm Thùy Dương', '0934567890', 'duong.pham@example.com', 'duongpt', 0, 1, 1),
('NV005', N'Hoàng Công Nam', '0945678901', 'nam.hoang@example.com', 'namhc', 1, 2, 1);
select * from NHANVIEN

-- Thêm dữ liệu cho bảng THANHTOAN
INSERT INTO THANHTOAN (PHUONGTHUC) VALUES
(1),
(2);

-- Thêm dữ liệu cho bảng SANPHAM
INSERT INTO SANPHAM (MASP, TEN, TRANGTHAI) VALUES
('SP001', N'Smart Tivi LG 4K 43 Inch 43UQ7050PSA',1),
('SP002', N'Google Tivi TCL 4K 55 inch 55P638',1),
('SP003', N'Android Tivi Panasonic 43 Inch TH-43LX650V',0),
('SP004', N'Smart Tivi Samsung 4K 43 Inch UA43BU8000',1),
('SP005', N'Google Tivi Xiaomi A Pro 4K 55 Inch L55M8-A2SEA',1);
select * from SANPHAM

-- Thêm dữ liệu cho bảng THUONGHIEU
INSERT INTO THUONGHIEU (MA, TEN, NGUONGOC) VALUES
('TH001', N'Samsung', N'Hàn Quốc'),
('TH002', N'Sony', N'Nhật Bản'),
('TH003', N'LG', N'Hàn Quốc'),
('TH004', N'TCL', N'Trung Quốc'),
('TH005', N'FFALCON', N'Trung Quốc'),
('TH006', N'Casper', N'Thái Lan');
select * from THUONGHIEU

-- Thêm dữ liệu cho bảng KIEUDANG
INSERT INTO KIEUDANG (MA, TEN) VALUES
('KD001', N'Màn Hình Phẳng'),
('KD002', N'Khung Tranh'),
('KD003', N'Màn Hình Cuộn');
select * from KIEUDANG

-- Thêm dữ liệu cho bảng LOAI
INSERT INTO LOAI (TEN) VALUES
(N'Cũ'),
(N'Mới');
SELECT * FROM LOAI

-- Thêm dữ liệu cho bảng KICHCO
INSERT INTO KICHCO (MA, Inch) VALUES
('KC001', 32),
('KC002', 33),
('KC003', 34),
('KC004', 35),
('KC005', 36),
('KC006', 37),
('KC007', 38),
('KC008', 39),
('KC009', 40),
('KC010', 41),
('KC011', 42);
select * from KICHCO
-- Thêm dữ liệu cho bảng MANHINH
INSERT INTO MANHINH (MA, TEN) VALUES
('MH001', N'OLED'),
('MH002', N'QLED'),
('MH003', N'MINI LED'),
('MH004', N'NanoCell');
select * from MANHINH

-- Thêm dữ liệu cho bảng DOPHANGIAI
INSERT INTO DOPHANGIAI (MA, TEN) VALUES
('DPG01', N'HD'),
('DPG02', N'FULL HD'),
('DPG03', N'4K'),
('DPG04', N'8K');
select * from DOPHANGIAI

-- Thêm dữ liệu cho bảng SANPHAMCHITIET
INSERT INTO SANPHAMCHITIET (MASPCT, ID_SP, ID_THUONGHIEU, ID_KIEUDANG, ID_LOAI, ID_KICHCO, ID_MANHINH, ID_PHANGIAI, SOLUONG, DONGIA, TRANGTHAI) VALUES
('SPCT1', 1, 1, 1, 1, 1, 1, 1, 100, 5000000,1),
('SPCT2', 2, 2, 2, 2, 2, 2, 2, 50, 6000000,1),
('SPCT3', 3, 3, 3, 1, 3, 3, 3, 30, 7000000,0),
('SPCT4', 4, 4, 2, 1, 4, 4, 4, 60, 8000000,1),
('SPCT5', 5, 5, 1, 2, 5, 1, 3, 50, 9000000,1);
select * from SANPHAMCHITIET

-- Thêm dữ liệu cho bảng HOADON
INSERT INTO HOADON (MAHD, ID_KH, ID_NV, ID_THANHTOAN,TEN, SODIENTHOAI, NGAY, TONGTIEN, TRANGTHAI) VALUES
('HD001', 1, 1, 1,N'Nguyễn Minh Anh', '0901234567',  '2023-01-01',null,1),
('HD002', 2, 2, 2,N'Trần Thu Hà', '0912345678', '2023-02-02',null,1),
('HD003', 3, 3, 1,N'Lê Văn Chiến', '0923456789', '2023-03-03',null,1),
('HD004', 4, 4, 2,N'Phạm Thùy Dương', '0934567890', '2023-04-04',null,1),
('HD005', 5, 5, 1,N'Hoàng Công Nam', '0945678901', '2023-05-05',null,1);

-- Thêm dữ liệu cho bảng HOADONCHITIET
INSERT INTO HOADONCHITIET (MAHDCT, ID_HD, ID_SPCT, SOLUONG, DONGIA) VALUES
('HDCT1', 1, 2, 2, 5000000),
('HDCT2', 2, 3, 3, 6000000),
('HDCT3', 3, 4, 1, 7000000),
('HDCT4', 4, 5, 4, 8000000),
('HDCT5', 5, 6, 5, 9000000);
select * from HOADONCHITIET

-- Thêm dữ liệu cho bảng PHIEUGIAMGIA
INSERT INTO PHIEUGIAMGIA (MAPHIEU, ID_HD, PHANTRAM, NGAYTAO, NGAYHETHAN,TRANGTHAI) VALUES
('PGG01', 1, 10, '2023-01-01', '2023-12-31',1),
('PGG02', 2, 20, '2023-02-02', '2023-12-31',1),
('PGG03', 3, 15, '2023-03-02', '2023-12-02',1);
select * from PHIEUGIAMGIA
SELECT spct.MASPCT, sp.TEN, spct.DONGIA, dpg.TEN, kc.Inch, th.TEN ,spct.SOLUONG
FROM SANPHAMCHITIET spct
INNER JOIN SANPHAM sp ON spct.ID_SP = sp.ID
INNER JOIN DOPHANGIAI dpg ON spct.ID_PHANGIAI = dpg.ID
INNER JOIN KICHCO kc ON spct.ID_KICHCO = kc.ID
INNER JOIN THUONGHIEU th ON spct.ID_THUONGHIEU = th.TEN
WHERE spct.ID = 1;
--ID_hoadon(hoadon), maHD(hoaDon), ngayTao(hoaDon), 

--ID_sanPham(spct), tenSanPham(sanrPham), soluong(spct), dongia(spct)
SELECT ctsp.ID, sp.TEN, ctsp.DONGIA, dpg.TEN, kc.Inch, th.TEN, ctsp.SOLUONG
FROM SANPHAMCHITIET ctsp
JOIN SANPHAM sp ON ctsp.ID_SP = sp.ID
JOIN DOPHANGIAI dpg ON ctsp.ID_PHANGIAI = dpg.ID
JOIN KICHCO kc ON ctsp.ID_KICHCO = kc.ID
JOIN THUONGHIEU th ON ctsp.ID_THUONGHIEU = th.ID

SELECT ID, MAHD, TONGTIEN FROM HOADON

UPDATE SANPHAMCHITIET SET SOLUONG = 30 WHERE ID = 2
UPDATE SANPHAMCHITIET SET TRANGTHAI = 1 WHERE ID = 9
DELETE HOADON WHERE ID = 11
/*
    private Integer Id;
    private int id_hd;
    private int id_spct;
    private String tenSanPham;
    private Integer SoLuong;
    private Integer DonGia;
*/

SELECT hdct.ID, hdct.ID_HD, hdct.ID_SPCT, sp.TEN, hdct.SOLUONG, hdct.DONGIA
FROM HOADONCHITIET hdct
INNER JOIN SANPHAMCHITIET ctsp ON hdct.ID_SPCT = ctsp.ID
INNER JOIN SANPHAM sp ON ctsp.ID_SP = sp.ID
WHERE hdct.ID_HD = 1;
SET IDENTITY_INSERT HOADON ON
SELECT ctsp.ID, sp.TEN, ctsp.DONGIA, dpg.TEN, kc.Inch, th.TEN, ctsp.SOLUONG
        FROM SANPHAMCHITIET ctsp
        JOIN SANPHAM sp ON ctsp.ID_SP = sp.ID
        JOIN DOPHANGIAI dpg ON ctsp.ID_PHANGIAI = dpg.ID
        JOIN KICHCO kc ON ctsp.ID_KICHCO = kc.ID
        JOIN THUONGHIEU th ON ctsp.ID_THUONGHIEU = th.ID
        WHERE ctsp.ID = 1 and sp.TEN LIKE ('Smart Tivi LG 4K 43 Inch 43UQ7050PSA')
		  
SELECT hd.ID, kh.TEN , kh.SODIENTHOAI , kh.DIACHI, hd.TONGTIEN 
FROM HOADON hd 
INNER JOIN KHACHHANG kh ON kh.ID = hd.ID_KH
WHERE hd.ID = 1

select * from HOADONCHITIET
delete HOADONCHITIET where ID = 27
select * from SANPHAMCHITIET
INSERT INTO HOADON (ID, TEN, SODIENTHOAI, NGAY, TRANGTHAI) VALUES (6, N'Hoàng Công Nam', '0934567890', '2023-01-01', 1)
select * from HOADON
select MAKH, TEN, SODIENTHOAI, DIACHI, GIOITINH, NGAYSINH from KHACHHANG
SELECT 
    HD.ID AS ID_HOADON,
    SUM(HDC.DONGIA * HDC.SOLUONG) AS TONGTIEN
FROM HOADON HD
JOIN HOADONCHITIET HDC ON HD.ID = HDC.ID_HD
GROUP BY HD.ID;