/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qltv.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qltv.dao.DBConnect;
import qltv.model.phieuGiamGia;
import qltv.service.giamGiaService;

public class phieuGiamGiaJPanel extends javax.swing.JPanel {
    public giamGiaService repo = new giamGiaService();
    public  ArrayList<phieuGiamGia> list = new ArrayList();
    /**
     * Creates new form phieuGiamGiaJPanel
     */
    public phieuGiamGiaJPanel() throws SQLException {
        initComponents();
        repo.updateTrangThai();
        this.loadData(repo.getAll(getOrder()));
    }
    
    public  void loadData(ArrayList<phieuGiamGia> inputlist) throws SQLException{ 
        list = inputlist;
        this.fillToTable();
    }
    
    public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tbl_GiamGia.getModel();
    model.setRowCount(0);
    for (phieuGiamGia phieu : list) {
        Object[] row = {
            phieu.getMaPhieu(),
            phieu.getIdHd(),
            phieu.getPhanTram(),
            phieu.getNgayTao(),
            phieu.getNgayHetHan(),
            phieu.getTrangThai() == 3 ? "Đã bị hủy" : phieu.getTrangThai() == 2 ? "Đã kết thúc" : phieu.getTrangThai() == 1 ? "Đang diễn ra" : "Sắp diễn ra"
        };
        model.addRow(row);
    }
}
    
    public String getOrder(){
        String Order = "MAPHIEU";
        switch (cbo_SapXep.getSelectedItem().toString()) {
            case "Mã":
                Order = "MAPHIEU";
                break;
            case "Loại":
                Order = "PHANTRAM";
                break;
            case "Ngày bắt đầu":
                Order = "NGAYTAO";
                break;
            case "Ngày kết thúc":
                Order = "NGAYKETTHUC";
                break;
            case "Trạng thái":
                Order = "TRANGTHAI";
                break;
        }
        
        return Order;
    }
    
    public boolean checkMa() throws SQLException{
        list = repo.getAll(getOrder());
        boolean check = false;
        for (phieuGiamGia phieu : list) {
            if(this.readForm().getMaPhieu().equalsIgnoreCase(phieu.getMaPhieu())){
                check = true;
            }
        }   
        return check;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_Ma = new javax.swing.JTextField();
        txt_HoaDon = new javax.swing.JTextField();
        txt_NgayBD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbo_Loai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_NgayHH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btn_Refresh = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_GiamGia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbo_Loc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbo_SapXep = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Ngày hết hạn:");

        txt_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HoaDonActionPerformed(evt);
            }
        });

        jLabel7.setText("Loại voucher:");

        jLabel8.setText("Ngày bắt đầu:");

        cbo_Loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20" }));
        cbo_Loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_LoaiActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã voucher:");

        jLabel4.setText("Hóa đơn:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btn_Refresh.setText("Làm mới");
        btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshActionPerformed(evt);
            }
        });

        btn_Huy.setText("Hủy");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_HoaDon)
                            .addComponent(txt_Ma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_NgayBD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_NgayHH, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbo_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_NgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NgayHH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_GiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Hóa đơn", "Loại", "Ngày bắt đầu", "Ngày hết hạn", "Trạng Thái"
            }
        ));
        tbl_GiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_GiamGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_GiamGia);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jLabel1.setText("Lọc theo:");

        cbo_Loc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang diễn ra", "Sắp diễn ra", "Đã kết thúc", "Đã bị hủy" }));
        cbo_Loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_LocActionPerformed(evt);
            }
        });

        jLabel2.setText("Sắp xếp theo:");

        cbo_SapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã", "Loại", "Ngày bắt đầu", "Ngày kết thúc ", "Trạng thái" }));
        cbo_SapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_SapXepActionPerformed(evt);
            }
        });

        jLabel5.setText("Tìm kiếm");

        txt_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimKiemActionPerformed(evt);
            }
        });

        btn_TimKiem.setText("Tìm ");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbo_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbo_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(cbo_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HoaDonActionPerformed

    private void cbo_LoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_LoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_LoaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            if (checkMa()== true) {
                JOptionPane.showMessageDialog(this, "Bạn đã nhập trùng mã");
            } else{
                if (txt_Ma.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(this, "Mã không được để trống");
                    }else if (txt_HoaDon.getText().trim().equals("")) {
                       JOptionPane.showMessageDialog(this, "Tên không được để trống");
        } else  if(repo.them(this.readForm()) > 0){
                repo.updateTrangThai();
                this.loadData(repo.getAll(getOrder()));
                JOptionPane.showMessageDialog(this,"Thêm thành công");
            }
            else    JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } catch (SQLException ex) {
            Logger.getLogger(khachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
                if (tbl_GiamGia.getSelectedRow() == -1) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn phiếu giảm giá để sửa");
                    }else if (txt_HoaDon.getText().trim().equals("")) {
                       JOptionPane.showMessageDialog(this, "Tên không được để trống");
        } else  if(repo.sua(this.readForm()) > 0){
                repo.updateTrangThai();
                this.loadData(repo.getAll(getOrder()));
                JOptionPane.showMessageDialog(this,"Sửa thành công");
            }
            else    JOptionPane.showMessageDialog(this, "Sửa thất bại");
            
        } catch (SQLException ex) {
            Logger.getLogger(khachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
         tbl_GiamGia.clearSelection();
    txt_Ma.setText("");
    txt_Ma.setEditable(true);
    txt_HoaDon.setText("");
    cbo_Loai.setSelectedIndex(0);
    txt_NgayBD.setText("");
    txt_NgayHH.setText("");
    cbo_Loc.setSelectedIndex(0);
    cbo_SapXep.setSelectedIndex(0);
    txt_TimKiem.setText("");
    
    try {
        repo.updateTrangThai();
        this.loadData(repo.getAll(getOrder()));
    } catch (SQLException ex) {
        Logger.getLogger(khachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_RefreshActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
            try {
                if (tbl_GiamGia.getSelectedRow() == -1) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn phiếu giảm giá để hủy");
                    }else if(repo.huy(this.readForm()) > 0){
                repo.updateTrangThai();
                this.loadData(repo.getAll(getOrder()));
                JOptionPane.showMessageDialog(this,"Hủy thành công");
            }
            else    JOptionPane.showMessageDialog(this, "Hủy thất bại");
            
        } catch (SQLException ex) {
            Logger.getLogger(khachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void txt_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimKiemActionPerformed

    private void tbl_GiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_GiamGiaMouseClicked
    int i = tbl_GiamGia.getSelectedRow();
    txt_Ma.setText(tbl_GiamGia.getValueAt(i, 0).toString());
    txt_Ma.setEditable(false);
    txt_HoaDon.setText(tbl_GiamGia.getValueAt(i, 1).toString());
    cbo_Loai.setSelectedItem(tbl_GiamGia.getValueAt(i, 2).toString());
    txt_NgayBD.setText(tbl_GiamGia.getValueAt(i, 3).toString());
    txt_NgayHH.setText(tbl_GiamGia.getValueAt(i, 4).toString());
    }//GEN-LAST:event_tbl_GiamGiaMouseClicked

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
     String input = txt_TimKiem.getText().toString().trim();
     int trangThai = -1;
        switch (cbo_Loc.getSelectedItem().toString()) {
            case "Tất cả":
                break;
            case "Đang diễn ra":
                trangThai = 1;
                break;             
            case "Sắp diễn ra":
                trangThai = 0;
                
                break;  
            case "Đã kết thúc":
                trangThai = 2;
                break;  
            case "Đã bị hủy":
                trangThai = 3;
                break;     
        }
        if (!input.isEmpty()) {
            try {
                if (!repo.timKiem(trangThai ,input, getOrder()).isEmpty()) {
                    JOptionPane.showMessageDialog(this, "tìm thấy");
                   
                    loadData(repo.timKiem(trangThai,input, getOrder()));
                } else {
                    JOptionPane.showMessageDialog(this, "ko tìm thấy");
                }
            } catch (SQLException ex) {
                Logger.getLogger(khachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
            JOptionPane.showMessageDialog(this, "ô tìm kiếm đang trống");
    
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void cbo_LocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_LocActionPerformed
    int trangThai = -1;
        try {
        switch (cbo_Loc.getSelectedItem().toString()) {
            case "Tất cả":
                break;
            case "Đang diễn ra":
                trangThai = 1;
                break;             
            case "Sắp diễn ra":
                trangThai = 0;
                
                break;  
            case "Đã kết thúc":
                trangThai = 2;
                break;  
            case "Đã bị hủy":
                trangThai = 3;
                break;     
        }
            if (trangThai== -1) {
                loadData(repo.getAll(getOrder()));
            } else {
                loadData(repo.loc(trangThai, getOrder()));
            }
    }  catch (SQLException ex) {
                Logger.getLogger(phieuGiamGiaJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    }//GEN-LAST:event_cbo_LocActionPerformed

    private void cbo_SapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_SapXepActionPerformed
        cbo_LocActionPerformed(evt);
    }//GEN-LAST:event_cbo_SapXepActionPerformed
public phieuGiamGia readForm() {
    String maPhieu = txt_Ma.getText().trim();
    int idHd = Integer.parseInt(txt_HoaDon.getText().trim());
    int phanTram = Integer.parseInt(cbo_Loai.getSelectedItem().toString());
    String ngayTao = txt_NgayBD.getText().trim();
    String ngayHetHan = txt_NgayHH.getText().trim();
    int trangThai = 0;
    // Giả định rằng "Loại voucher" là một JComboBox và chỉ chứa các lựa chọn "Giảm theo %" và một loại khác

    return new phieuGiamGia(maPhieu, idHd, phanTram, ngayTao, ngayHetHan, trangThai);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JComboBox<String> cbo_Loai;
    private javax.swing.JComboBox<String> cbo_Loc;
    private javax.swing.JComboBox<String> cbo_SapXep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_GiamGia;
    private javax.swing.JTextField txt_HoaDon;
    private javax.swing.JTextField txt_Ma;
    private javax.swing.JTextField txt_NgayBD;
    private javax.swing.JTextField txt_NgayHH;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
